CREATE TABLE EVENT(
EVENT_ID NUMBER ,
EVENT_NAME VARCHAR(100)
);

CREATE TABLE GUEST(
GUEST_ID NUMBER ,
GUEST_FIRST_NAME VARCHAR(100),
GUEST_SECOND_NAME VARCHAR(100),
GUEST_CARD_NUMBER NUMBER
);

CREATE TABLE ORDERING (
ORDER_ID NUMBER,
ORDER_EVENT_ID NUMBER,
ORDER_GUEST_ID NUMBER
);